### ISSUE TITLE
Property binding[] is not working when we call angular element from parent project 

### ISSUE THREAD

**Issue by subham-subhasis** [angular-extensions/elements#50] opened 2020-05-13 09:35 UTC
1. I have an element named element-setpassword
2. i have place it in the assests of route application after build
3. when i try to send data from parent to  element it is failing if i am using property binding. example below
 <element-setPassword id="element-set-password" *axLazyElement="elementUrl" [usernamevalue]="name"></element-setPassword>  --> failing 

<element-setPassword id="element-set-password" *axLazyElement="elementUrl" usernamevalue="subham"></element-setPassword>  --> working

**Comment by tomastrajan** [comment] 2020-05-14 14:13
@subham-subhasis hard to say what is wrong, such use case is up and running in showcase and also in many projects I was working on professionaly.

My best guess is that it is a problem with how the element was implemented.

Wish you good luck!

**Comment by MagicCurlyHair** [comment] 2020-05-18 17:05
Hi @subham-subhasis @tomastrajan 
I can confirm I have encountered this issue as well. I previously had some issues with property binding and custom elements but always managed to find workarounds.
I think I may have found a one-line fix for this, will try to submit a PR today.

**Comment by tomastrajan** [comment] 2020-05-19 15:30
@MagicCurlyHair thx for the PR, @subham-subhasis please, see the PR for details.

**Closed** 2020-05-19 17:23 UTC

**Comment by subham-subhasis** [comment] 2020-05-19 17:25
I have used attr. attribute what I want to send , it worked. _ know its a silly thing &  tried all the things to fix that.

Thanks everyone for sharing your time to fix this.

**Comment by FinalVersion** [comment] 2020-06-15 14:28
@MagicCurlyHair I believe I encountered the same issue. When passing as static attribute, the custom element (created by angular elements) can receive it as input, when passing as property binding, the custom element get undefined input value. Can I use your patch without having to upgrade to Angular 10?

**Comment by MagicCurlyHair** [comment] 2020-06-15 20:20
@FinalVersion sure, it's actually build with Angular 9. The only reason for major version bump is that the change is potentially breaking but that shouldn't be the problem for the intended use case. Please leave a comment in the PR whether it fixes your issue.

**Comment by tomastrajan** [comment] 2020-06-28 22:41
@FinalVersion the version 10.0.0 for Angular 10 was released just now, please feel free to try it in your project!
